#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.luci_app_pptp_server
	set firewall.luci_app_pptp_server=include
	set firewall.luci_app_pptp_server.type=script
	set firewall.luci_app_pptp_server.path=/var/etc/luci-app-pptp-server.include
	set firewall.luci_app_pptp_server.reload=1
	commit firewall
EOF

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@luci-app-pptp-server[-1]
	add ucitrack luci-app-pptp-server
	set ucitrack.@luci-app-pptp-server[-1].init=luci-app-pptp-server
	commit ucitrack
EOF

echo "net.netfilter.nf_conntrack_helper=1" > /etc/sysctl.d/13-pptp-gre.conf
#echo "iptables -t nat -I PREROUTING -p gre -j DNAT" >> /etc/firewall.user

rm -rf /tmp/luci-*cache
exit 0
